apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: websocketserver-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffer-size: "256k"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/proxy-busy-buffers-size: "256k"
    nginx.ingress.kubernetes.io/large-client-header-buffers: "4 16k"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "2592000"  # 30 days
    nginx.ingress.kubernetes.io/proxy-send-timeout: "2592000"  # 30 days
spec:
  ingressClassName: nginx
  tls:
    - hosts:
      - websocketserver.kub.lab
      secretName: labcert-secret
  rules:
  - host: "websocketserver.kub.lab"
    http:
      paths:
      - pathType: ImplementationSpecific
        backend:
          service:
            name: websocketserver-service
            port:
              number: 80