apiVersion: v1
kind: Service
metadata:
  name: websocketserver-service
  namespace: default
spec:
  selector:
    app: websocketserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000